os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

before_install:
- export TM_VERSION=0.21.0
- export BOV_VERSION=v0.5.1
# macOS/Linux compatible temp dir deleted on reboot (https://stackoverflow.com/a/31397073)
- |
  export TM_DIR=$(mktemp -d "${TMPDIR:-/tmp}/tendermint_${TM_VERSION}.XXXXXXXXX")
  export BOV_DIR=$(mktemp -d "${TMPDIR:-/tmp}/bov_${BOV_VERSION}.XXXXXXXXX")
  echo "TM_DIR = $TM_DIR"
  echo "BOV_DIR = $BOV_DIR"
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
    # add dependencies to compile node-hid (no prebuilt available)
    sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    npm install -g node-gyp
  fi
# detect whether we can use docker, but don't fail if impossible
# this currently passes on linux, fails on osx
- docker pull tendermint/tendermint:${TM_VERSION} && export TENDERMINT_ENABLED=1 || true
- docker pull iov1/tendermint:${TM_VERSION} && docker pull iov1/bov:${BOV_VERSION} && export BOV_ENABLED=1 || true

install:
- yarn install

before_script:
- |
  if [[ $TENDERMINT_ENABLED ]]; then
    ./packages/iov-tendermint-rpc/tendermint.sh > /tmp/foo.log &
    export TM_PID=$!
    echo "Started tendermint" $TM_PID
    sleep 2
  fi
- |
  if [[ $BOV_ENABLED ]]; then
    ./packages/iov-bns/bov_init.sh
    ./packages/iov-bns/bov_tm.sh > /tmp/bov_tm.log &
    export BOV_TM_PID=$!
    ./packages/iov-bns/bov_app.sh > /tmp/bov_app.log &
    export BOV_APP_PID=$!
    sleep 3
    # for debug output
    cat /tmp/bov_tm.log
    cat /tmp/bov_app.log
  fi

script:
- echo "use tendermint?" ${TENDERMINT_ENABLED} "use bov?" ${BOV_ENABLED}
- ./travis.sh

after_script:
- |
  if [[ $TM_PID ]]; then
    echo "Stopping tendermint" $TM_PID
    kill ${TM_PID}
  fi
- |
  if [[ $BOV_APP_PID ]]; then
    echo "Stopping bov"
    kill ${BOV_APP_PID}
    kill ${BOV_TM_PID}
    # for debug output
    cat /tmp/bov_app.log
  fi

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
