os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

before_install:
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
  fi
# add dependencies to compile node-hid
- sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
- sudo npm install -g node-gyp

install:
- yarn install

script:
- ./travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
