os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

script:
- ./travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
