os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

before_install:
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
    # add dependencies to compile node-hid (no prebuilt available)
    sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    npm install -g node-gyp
  fi
- export TM_VERSION=0.20.0
- docker pull tendermint/tendermint:${TM_VERSION}

install:
- yarn install

before_script:
- ./packages/tendermint-rpc/tendermint.sh > /tmp/foo.log &
- export TM_PID=$!
- echo "Started tendermint" $TM_PID
- export TENDERMINT_ENABLED=1
- sleep 2
# for debug output
- cat /tmp/foo.log

script:
- echo "use tendermint?" ${TENDERMINT_ENABLED}
- ./travis.sh

after_script:
- echo "Stopping tendermint" $TM_PID
- kill ${TM_PID}
# - cat /tmp/foo.log

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
