os:
  - linux
  - osx

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

before_install:
- export TM_VERSION=0.20.0
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
    # add dependencies to compile node-hid (no prebuilt available)
    sudo apt-get install -y libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    npm install -g node-gyp
  fi
# detect whether we can use docker, but don't fail if impossible
# this currently passes on linux, fails on osx
- (docker pull tendermint/tendermint:${TM_VERSION} && export TENDERMINT_ENABLED=1) || true

install:
- yarn install

before_script:
- |
  if [[ $TENDERMINT_ENABLED ]]; then
    ./packages/tendermint-rpc/tendermint.sh > /tmp/foo.log &
    export TM_PID=$!
    echo "Started tendermint" $TM_PID
    sleep 2
    # for debug output
    cat /tmp/foo.log
  fi

script:
- echo "use tendermint?" ${TENDERMINT_ENABLED}
- ./travis.sh

after_script:
- |
  if [[ $TM_PID ]]; then
    echo "Stopping tendermint" $TM_PID
    kill ${TM_PID}
  fi

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
