os:
  - linux
  - osx

language: node_js
node_js:
  - "8"

addons:
  firefox: latest
  chrome: stable

script:
- ./travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master

notifications:
  email: false
